import { Airdrop } from './supabase';

// Comprehensive mock airdrop data based on the research
export const mockAirdrops: Airdrop[] = [
  // High-Potential Upcoming Airdrops (2025)
  {
    id: '1',
    name: 'zkSync Era',
    description: 'Layer 2 scaling solution using ZK-rollups technology with mainnet active and token expected',
    category: 'Layer 2',
    status: 'upcoming',
    blockchain: 'Ethereum',
    token_symbol: 'ZK',
    estimated_value: '$500-2,000',
    eligibility_criteria: ['Early users', 'DeFi participants', 'NFT minters'],
    requirements: ['Bridge assets to zkSync', 'Use dApps on zkSync', 'Maintain regular activity'],
    official_website: 'https://zksync.io/',
    twitter_handle: '@zksync',
    discord_link: 'https://discord.gg/zksync',
    telegram_link: 'https://t.me/zksync',
    contract_address: '',
    distribution_date: new Date('2025-03-01').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 10,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '2',
    name: 'StarkNet',
    description: 'ZK-rollup Layer 2 solution focused on scalability and developer experience',
    category: 'Layer 2',
    status: 'upcoming',
    blockchain: 'Ethereum',
    token_symbol: 'STRK',
    estimated_value: '$500-2,000',
    eligibility_criteria: ['Active developers', 'Power users', 'dApp users'],
    requirements: ['Use StarkNet dApps', 'Deploy contracts', 'Maintain activity'],
    official_website: 'https://starknet.io/',
    twitter_handle: '@StarkNet',
    discord_link: 'https://discord.gg/starknet',
    telegram_link: 'https://t.me/starknet',
    contract_address: '',
    distribution_date: new Date('2025-02-15').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '3',
    name: 'Blast',
    description: 'Layer 2 solution with native yield for ETH and stablecoins',
    category: 'Layer 2',
    status: 'upcoming',
    blockchain: 'Ethereum',
    estimated_value: '$500-2,000',
    eligibility_criteria: ['Early users', 'DeFi participants'],
    requirements: ['Bridge assets to Blast', 'Use native yield features', 'Maintain activity'],
    official_website: 'https://blast.io/',
    twitter_handle: '@Blast_L2',
    discord_link: 'https://discord.gg/blast',
    telegram_link: 'https://t.me/blast',
    contract_address: '',
    distribution_date: new Date('2025-01-20').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '4',
    name: 'EigenLayer',
    description: 'Ethereum restaking protocol enabling shared security',
    category: 'Infrastructure',
    status: 'upcoming',
    blockchain: 'Ethereum',
    token_symbol: 'EIGEN',
    estimated_value: '$500-3,000',
    eligibility_criteria: ['ETH stakers', 'Restakers', 'Node operators'],
    requirements: ['Restake ETH through EigenLayer', 'Operate nodes', 'Maintain activity'],
    official_website: 'https://www.eigenlayer.xyz/',
    twitter_handle: '@EigenLayer',
    discord_link: 'https://discord.gg/eigenlayer',
    telegram_link: 'https://t.me/eigenlayer',
    contract_address: '',
    distribution_date: new Date('2025-02-28').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 10,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '5',
    name: 'Linea',
    description: 'Consensys-backed Layer 2 solution focused on Ethereum compatibility',
    category: 'Layer 2',
    status: 'upcoming',
    blockchain: 'Ethereum',
    estimated_value: '$300-1,500',
    eligibility_criteria: ['Testnet users', 'Early mainnet users', 'dApp participants'],
    requirements: ['Bridge ETH to Linea', 'Use Linea dApps', 'Maintain activity'],
    official_website: 'https://linea.build/',
    twitter_handle: '@LineaBuild',
    discord_link: 'https://discord.gg/linea',
    telegram_link: 'https://t.me/lineabuild',
    contract_address: '',
    distribution_date: new Date('2025-01-15').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 8,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '6',
    name: 'Uniswap V4',
    description: 'Next version of Uniswap with hooks functionality',
    category: 'DeFi',
    status: 'upcoming',
    blockchain: 'Ethereum',
    estimated_value: '$1,000-5,000',
    eligibility_criteria: ['Hook developers', 'Early LPs', 'Active traders'],
    requirements: ['Develop hooks', 'Provide liquidity', 'Test new features'],
    official_website: 'https://uniswap.org/',
    twitter_handle: '@Uniswap',
    discord_link: 'https://discord.gg/uniswap',
    telegram_link: 'https://t.me/uniswap',
    contract_address: '',
    distribution_date: new Date('2025-06-01').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '7',
    name: 'Farcaster',
    description: 'Decentralized social network protocol with potential token',
    category: 'Social',
    status: 'upcoming',
    blockchain: 'Ethereum',
    estimated_value: '$300-1,500',
    eligibility_criteria: ['Active users', 'Content creators', 'Early adopters'],
    requirements: ['Regular posting', 'Engagement', 'Build social presence'],
    official_website: 'https://www.farcaster.xyz/',
    twitter_handle: '@farcaster',
    discord_link: 'https://discord.gg/farcaster',
    telegram_link: 'https://t.me/farcaster',
    contract_address: '',
    distribution_date: new Date('2025-03-15').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 8,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '8',
    name: 'Lens Protocol',
    description: 'Decentralized social graph protocol',
    category: 'Social',
    status: 'upcoming',
    blockchain: 'Polygon',
    estimated_value: '$200-1,000',
    eligibility_criteria: ['Content creators', 'Active users', 'Profile owners'],
    requirements: ['Create Lens profile', 'Publish content', 'Engage with others'],
    official_website: 'https://www.lens.xyz/',
    twitter_handle: '@LensProtocol',
    discord_link: 'https://discord.gg/lens',
    telegram_link: 'https://t.me/lens',
    contract_address: '',
    distribution_date: new Date('2025-04-01').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: false,
    priority: 7,
    potential_rating: 'medium',
    china_restricted: false
  },
  {
    id: '9',
    name: 'ParaSwap',
    description: 'Decentralized exchange aggregator with potential token launch',
    category: 'DeFi',
    status: 'upcoming',
    blockchain: 'Multi-chain',
    estimated_value: '$200-1,000',
    eligibility_criteria: ['Active traders', 'Liquidity providers'],
    requirements: ['Use ParaSwap for swaps', 'Provide liquidity', 'Maintain volume'],
    official_website: 'https://paraswap.io/',
    twitter_handle: '@ParaSwap',
    discord_link: 'https://discord.gg/paraswap',
    telegram_link: 'https://t.me/paraswap',
    contract_address: '',
    distribution_date: new Date('2025-05-01').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: false,
    priority: 7,
    potential_rating: 'medium',
    china_restricted: false
  },
  {
    id: '10',
    name: 'Pixelmon',
    description: 'Web3 gaming project with NFT integration',
    category: 'Gaming',
    status: 'upcoming',
    blockchain: 'Ethereum',
    estimated_value: '$100-500',
    eligibility_criteria: ['NFT holders', 'Game participants', 'Community members'],
    requirements: ['Hold Pixelmon NFTs', 'Participate in games', 'Community engagement'],
    official_website: 'https://pixelmon.xyz/',
    twitter_handle: '@pixelmon',
    discord_link: 'https://discord.gg/pixelmon',
    telegram_link: 'https://t.me/pixelmon',
    contract_address: '',
    distribution_date: new Date('2025-04-15').toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: false,
    priority: 6,
    potential_rating: 'medium',
    china_restricted: false
  },

  // Successful Past Airdrops (Case Studies)
  {
    id: '11',
    name: 'Uniswap',
    description: 'Leading decentralized exchange protocol',
    category: 'DeFi',
    status: 'distributed',
    blockchain: 'Ethereum',
    token_symbol: 'UNI',
    estimated_value: '$1,500 at launch',
    eligibility_criteria: ['Historical users', 'Liquidity providers', 'Traders'],
    requirements: ['Swapped tokens', 'Provided liquidity', 'Voted in governance'],
    official_website: 'https://uniswap.org/',
    twitter_handle: '@Uniswap',
    discord_link: 'https://discord.gg/uniswap',
    telegram_link: 'https://t.me/uniswap',
    contract_address: '',
    distribution_date: '2020-09-17',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 10,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '12',
    name: 'Arbitrum',
    description: 'Leading Layer 2 optimistic rollup solution',
    category: 'Layer 2',
    status: 'distributed',
    blockchain: 'Ethereum',
    token_symbol: 'ARB',
    estimated_value: '$1,250',
    eligibility_criteria: ['DAO voters', 'Bridge users', 'dApp users'],
    requirements: ['Bridged assets', 'Used dApps', 'Voted in governance'],
    official_website: 'https://arbitrum.io/',
    twitter_handle: '@arbitrum',
    discord_link: 'https://discord.gg/arbitrum',
    telegram_link: 'https://t.me/arbitrum',
    contract_address: '',
    distribution_date: '2023-03-23',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 10,
    potential_rating: 'very_high',
    china_restricted: false
  },
  {
    id: '13',
    name: 'Optimism',
    description: 'Layer 2 scaling solution for Ethereum',
    category: 'Layer 2',
    status: 'distributed',
    blockchain: 'Ethereum',
    token_symbol: 'OP',
    estimated_value: '$700-1,000',
    eligibility_criteria: ['Early users', 'DAO voters', 'Ecosystem contributors'],
    requirements: ['Used Optimism', 'Governance participation', 'Ecosystem activity'],
    official_website: 'https://www.optimism.io/',
    twitter_handle: '@optimismPBC',
    discord_link: 'https://discord.gg/optimism',
    telegram_link: 'https://t.me/optimism',
    contract_address: '',
    distribution_date: '2022-05-31',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '14',
    name: 'dYdX',
    description: 'Decentralized perpetual trading platform',
    category: 'DeFi',
    status: 'distributed',
    blockchain: 'Ethereum',
    token_symbol: 'DYDX',
    estimated_value: '$1,200-3,000',
    eligibility_criteria: ['Traders', 'Active users'],
    requirements: ['Trading volume', 'Platform activity', 'Historical usage'],
    official_website: 'https://dydx.exchange/',
    twitter_handle: '@dydxprotocol',
    discord_link: 'https://discord.gg/dydx',
    telegram_link: 'https://t.me/dydx',
    contract_address: '',
    distribution_date: '2021-08-03',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '15',
    name: 'Aptos',
    description: 'Layer 1 blockchain focused on scalability and safety',
    category: 'Infrastructure',
    status: 'distributed',
    blockchain: 'Aptos',
    token_symbol: 'APT',
    estimated_value: '$300-500',
    eligibility_criteria: ['Testnet participants', 'Early mainnet users'],
    requirements: ['Testnet participation', 'Early adoption', 'Community engagement'],
    official_website: 'https://aptoslabs.com/',
    twitter_handle: '@Aptos_Network',
    discord_link: 'https://discord.gg/aptos',
    telegram_link: 'https://t.me/aptos',
    contract_address: '',
    distribution_date: '2022-10-18',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 8,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '16',
    name: 'Blur',
    description: 'NFT marketplace and aggregator',
    category: 'DeFi',
    status: 'distributed',
    blockchain: 'Ethereum',
    token_symbol: 'BLUR',
    estimated_value: 'Variable based on trading volume',
    eligibility_criteria: ['NFT traders', 'Liquidity providers'],
    requirements: ['NFT trading volume', 'Platform usage'],
    official_website: 'https://www.blur.io/',
    twitter_handle: '@blur_io',
    discord_link: 'https://discord.gg/blur',
    telegram_link: 'https://t.me/blur',
    contract_address: '',
    distribution_date: '2023-02-14',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 8,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '17',
    name: 'Celestia',
    description: 'Modular data availability network',
    category: 'Infrastructure',
    status: 'distributed',
    blockchain: 'Celestia',
    token_symbol: 'TIA',
    estimated_value: '$50-200',
    eligibility_criteria: ['Testnet users', 'Community members'],
    requirements: ['Testnet participation', 'Community contributions'],
    official_website: 'https://celestia.org/',
    twitter_handle: '@CelestiaOrg',
    discord_link: 'https://discord.gg/celestia',
    telegram_link: 'https://t.me/celestia',
    contract_address: '',
    distribution_date: '2023-10-31',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 8,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '18',
    name: 'LayerZero',
    description: 'Omnichain interoperability protocol',
    category: 'Infrastructure',
    status: 'distributed',
    blockchain: 'Multi-chain',
    token_symbol: 'ZRO',
    estimated_value: '$500-2,000',
    eligibility_criteria: ['Power users', 'Developers', 'Cross-chain activity'],
    requirements: ['Cross-chain transactions', 'Bridge usage', 'dApp integration'],
    official_website: 'https://layerzero.network/',
    twitter_handle: '@LayerZero_Labs',
    discord_link: 'https://discord.gg/layerzero',
    telegram_link: 'https://t.me/layerzero',
    contract_address: '',
    distribution_date: '2024-06-20',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: true,
    priority: 9,
    potential_rating: 'high',
    china_restricted: false
  },
  {
    id: '19',
    name: 'Sei',
    description: 'Layer 1 blockchain focused on DeFi and gaming',
    category: 'Infrastructure',
    status: 'distributed',
    blockchain: 'Sei',
    token_symbol: 'SEI',
    estimated_value: '$200-500',
    eligibility_criteria: ['Testnet participants', 'Community members'],
    requirements: ['Testnet usage', 'Community engagement'],
    official_website: 'https://www.seinetwork.io/',
    twitter_handle: '@seinetwork',
    discord_link: 'https://discord.gg/sei',
    telegram_link: 'https://t.me/sei',
    contract_address: '',
    distribution_date: '2023-08-15',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: false,
    priority: 7,
    potential_rating: 'medium',
    china_restricted: false
  },
  {
    id: '20',
    name: 'Illuvium',
    description: 'Open-world RPG blockchain game',
    category: 'Gaming',
    status: 'distributed',
    blockchain: 'Immutable X',
    estimated_value: '$200-1,000',
    eligibility_criteria: ['Active players', 'Landowners', 'Beta testers'],
    requirements: ['Play the game', 'Own land', 'Participate in beta'],
    official_website: 'https://illuvium.io/',
    twitter_handle: '@illuviumio',
    discord_link: 'https://discord.gg/illuvium',
    telegram_link: 'https://t.me/illuvium',
    contract_address: '',
    distribution_date: '2024-01-15',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    featured: false,
    priority: 7,
    potential_rating: 'medium',
    china_restricted: false
  }
];